apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdia.fullname" . }}-orchestrator
  labels:
    {{- include "sdia.labels" . | nindent 4 }}-orchestrator
spec:
  {{- if not .Values.orchestrator.autoscaling.enabled }}
  replicas: {{ .Values.orchestrator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sdia.selectorLabels" . | nindent 6 }}-orchestrator
  template:
    metadata:
      {{- with .Values.orchestrator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sdia.selectorLabels" . | nindent 8 }}-orchestrator
    spec:
      {{- with .Values.orchestrator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sdia.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.orchestrator.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-orchestrator
          securityContext:
            {{- toYaml .Values.orchestrator.securityContext | nindent 12 }}
          image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.orchestrator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /orchestrator/tosca_template/ids
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /orchestrator/tosca_template/ids
#              port: http
          resources:
            {{- toYaml .Values.orchestrator.resources | nindent 12 }}
      {{- with .Values.orchestrator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.orchestrator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.orchestrator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
