apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdia.fullname" . }}-sure
  labels:
    {{- include "sdia.labels" . | nindent 4 }}-sure
spec:
  type: {{ .Values.sure.service.type }}
  ports:
    - port: {{ .Values.sure.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sdia.selectorLabels" . | nindent 4 }}-sure
